os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release
  
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
  - set /p VCPKGS=<.appveyor_vcpkgs
  - vcpkg install %VCPKGS%

cache: c:\tools\vcpkg\installed\ -> .appveyor_vcpkgs

build_script:
#  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
#  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
#  - cd C:\projects\fluidsynth
  - mkdir build
  - cd build
  - cmake -G "%generator%" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . --config Release
  
#after_build:
#  - 7z a fluidsynth.zip %APPVEYOR_BUILD_FOLDER%\build\src\Release\* c:\deps\bin\libglib*.dll c:\deps\bin\libgthread*.dll c:\deps\bin\*intl*.dll

#artifacts:
#  - path: build/fluidsynth.zip
#    name: FluidSynth
