os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release

environment:
#  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
      - platform: x86
        generator: Visual Studio 14 2015

      - platform: x64
        generator: Visual Studio 14 2015 Win64
  
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
  - cd c:\tools\vcpkg\installed\
  - curl -fsS -o c:\deps.zip http://www.midigurdy.com/deps.zip
  - 7z x deps.zip
  - vcpkg install glib:x86-windows
  - vcpkg install glib:x64-windows

# cache: c:\tools\vcpkg\installed\ -> .appveyor_cache

build_script:
  - cd c:\projects\fluidsynth
  - mkdir build
  - cd build
  - cmake -G "%generator%" -Denable-pkgconfig=0 %cmake-args% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . --config Release
  
after_build:
  - 7z a fluidsynth.zip %APPVEYOR_BUILD_FOLDER%\build\src\Release\*

artifacts:
  - path: build/fluidsynth.zip
    name: FluidSynth
